export const SlideList = [
  {
    name: "osama",
    alt: "Mr",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 234,
    bedroomNumber: 7,
    bathroomNumber: 4,
    monthDay: "Month",
    squareMeter: 334,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "osama",
    alt: "Mr",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 3687,
    bedroomNumber: 6,
    bathroomNumber: 3,
    monthDay: "Year",
    squareMeter: 808,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "tala",
    alt: "Ms",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 5028,
    bedroomNumber: 0,
    bathroomNumber: 6,
    monthDay: "Month",
    squareMeter: 384,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "osama",
    alt: "Mr",
    typeProperty: "Chalet",
    propertyCondition: "For rent",
    price: 3272,
    bedroomNumber: 1,
    bathroomNumber: 1,
    monthDay: "Month",
    squareMeter: 798,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "osama",
    alt: "Honorable",
    typeProperty: "Camp",
    propertyCondition: "For sale",
    price: 7753,
    bedroomNumber: 5,
    bathroomNumber: 10,
    monthDay: "Year",
    squareMeter: 860,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "ahmed",
    alt: "Dr",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 646,
    bedroomNumber: 5,
    bathroomNumber: 3,
    monthDay: "Week",
    squareMeter: 382,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "ahmed",
    alt: "Ms",
    typeProperty: "Camp",
    propertyCondition: "For sale",
    price: 1571,
    bedroomNumber: 6,
    bathroomNumber: 0,
    monthDay: "Week",
    squareMeter: 148,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "ahmed",
    alt: "Mrs",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 9729,
    bedroomNumber: 1,
    bathroomNumber: 3,
    monthDay: "Month",
    squareMeter: 217,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "anas",
    alt: "Ms",
    typeProperty: "Land",
    propertyCondition: "For sale",
    price: 9325,
    bedroomNumber: 4,
    bathroomNumber: 2,
    monthDay: "Week",
    squareMeter: 419,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "malek",
    alt: "Mrs",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 6696,
    bedroomNumber: 10,
    bathroomNumber: 3,
    monthDay: "Year",
    squareMeter: 104,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "omar",
    alt: "Mr",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 4325,
    bedroomNumber: 7,
    bathroomNumber: 9,
    monthDay: "Month",
    squareMeter: 779,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "tala",
    alt: "Rev",
    typeProperty: "Camp",
    propertyCondition: "For rent",
    price: 6003,
    bedroomNumber: 7,
    bathroomNumber: 9,
    monthDay: "Month",
    squareMeter: 967,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "anas",
    alt: "Mrs",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 6435,
    bedroomNumber: 8,
    bathroomNumber: 3,
    monthDay: "Day",
    squareMeter: 371,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "hamza",
    alt: "Mrs",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 9450,
    bedroomNumber: 8,
    bathroomNumber: 3,
    monthDay: "Month",
    squareMeter: 527,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "hamza",
    alt: "Mr",
    typeProperty: "Camp",
    propertyCondition: "For rent",
    price: 723,
    bedroomNumber: 1,
    bathroomNumber: 7,
    monthDay: "Week",
    squareMeter: 698,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "hamza",
    alt: "Honorable",
    typeProperty: "Chalet",
    propertyCondition: "For rent",
    price: 4079,
    bedroomNumber: 8,
    bathroomNumber: 10,
    monthDay: "Week",
    squareMeter: 69,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "hamza",
    alt: "Dr",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 7115,
    bedroomNumber: 7,
    bathroomNumber: 2,
    monthDay: "Year",
    squareMeter: 651,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "omar",
    alt: "Honorable",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 4239,
    bedroomNumber: 8,
    bathroomNumber: 7,
    monthDay: "Week",
    squareMeter: 606,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "ahmed",
    alt: "Mr",
    typeProperty: "Land",
    propertyCondition: "For sale",
    price: 9723,
    bedroomNumber: 0,
    bathroomNumber: 0,
    monthDay: "Year",
    squareMeter: 269,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "omar",
    alt: "Dr",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 2799,
    bedroomNumber: 4,
    bathroomNumber: 2,
    monthDay: "Month",
    squareMeter: 838,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "ahmed",
    alt: "Rev",
    typeProperty: "Camp",
    propertyCondition: "For sale",
    price: 5645,
    bedroomNumber: 8,
    bathroomNumber: 8,
    monthDay: "Day",
    squareMeter: 431,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "hamza",
    alt: "Mrs",
    typeProperty: "Chalet",
    propertyCondition: "For rent",
    price: 2287,
    bedroomNumber: 3,
    bathroomNumber: 8,
    monthDay: "Day",
    squareMeter: 406,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "malek",
    alt: "Dr",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 1949,
    bedroomNumber: 7,
    bathroomNumber: 8,
    monthDay: "Week",
    squareMeter: 492,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "tala",
    alt: "Mr",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 4769,
    bedroomNumber: 4,
    bathroomNumber: 3,
    monthDay: "Day",
    squareMeter: 765,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "hamza",
    alt: "Ms",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 4191,
    bedroomNumber: 8,
    bathroomNumber: 10,
    monthDay: "Day",
    squareMeter: 270,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "malek",
    alt: "Honorable",
    typeProperty: "Land",
    propertyCondition: "For sale",
    price: 7445,
    bedroomNumber: 9,
    bathroomNumber: 2,
    monthDay: "Year",
    squareMeter: 639,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "malek",
    alt: "Rev",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 2175,
    bedroomNumber: 1,
    bathroomNumber: 8,
    monthDay: "Month",
    squareMeter: 0,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "ahmed",
    alt: "Mr",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 2938,
    bedroomNumber: 10,
    bathroomNumber: 10,
    monthDay: "Day",
    squareMeter: 594,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "omar",
    alt: "Mr",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 1988,
    bedroomNumber: 6,
    bathroomNumber: 8,
    monthDay: "Month",
    squareMeter: 378,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "omar",
    alt: "Mrs",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 9207,
    bedroomNumber: 10,
    bathroomNumber: 0,
    monthDay: "Day",
    squareMeter: 528,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
  {
    name: "anas",
    alt: "Mr",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 8042,
    bedroomNumber: 6,
    bathroomNumber: 10,
    monthDay: "Month",
    squareMeter: 110,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "osama",
    alt: "Dr",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 2465,
    bedroomNumber: 9,
    bathroomNumber: 10,
    monthDay: "Month",
    squareMeter: 69,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "omar",
    alt: "Honorable",
    typeProperty: "Camp",
    propertyCondition: "For sale",
    price: 3279,
    bedroomNumber: 5,
    bathroomNumber: 1,
    monthDay: "Month",
    squareMeter: 888,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "malek",
    alt: "Ms",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 5662,
    bedroomNumber: 2,
    bathroomNumber: 7,
    monthDay: "Week",
    squareMeter: 398,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "anas",
    alt: "Ms",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 8213,
    bedroomNumber: 1,
    bathroomNumber: 9,
    monthDay: "Year",
    squareMeter: 821,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "malek",
    alt: "Ms",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 1155,
    bedroomNumber: 6,
    bathroomNumber: 9,
    monthDay: "Week",
    squareMeter: 890,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "hamza",
    alt: "Mr",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 4531,
    bedroomNumber: 1,
    bathroomNumber: 8,
    monthDay: "Week",
    squareMeter: 482,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "ahmed",
    alt: "Honorable",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 4115,
    bedroomNumber: 1,
    bathroomNumber: 0,
    monthDay: "Day",
    squareMeter: 983,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
  {
    name: "tala",
    alt: "Mr",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 2738,
    bedroomNumber: 2,
    bathroomNumber: 0,
    monthDay: "Month",
    squareMeter: 643,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "osama",
    alt: "Ms",
    typeProperty: "Camp",
    propertyCondition: "For sale",
    price: 6695,
    bedroomNumber: 3,
    bathroomNumber: 5,
    monthDay: "Week",
    squareMeter: 971,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "tala",
    alt: "Ms",
    typeProperty: "Camp",
    propertyCondition: "For sale",
    price: 6381,
    bedroomNumber: 8,
    bathroomNumber: 6,
    monthDay: "Year",
    squareMeter: 360,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "anas",
    alt: "Rev",
    typeProperty: "Camp",
    propertyCondition: "For rent",
    price: 2016,
    bedroomNumber: 2,
    bathroomNumber: 6,
    monthDay: "Year",
    squareMeter: 122,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "omar",
    alt: "Mrs",
    typeProperty: "Camp",
    propertyCondition: "For rent",
    price: 3321,
    bedroomNumber: 0,
    bathroomNumber: 7,
    monthDay: "Week",
    squareMeter: 427,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "hamza",
    alt: "Rev",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 995,
    bedroomNumber: 3,
    bathroomNumber: 10,
    monthDay: "Month",
    squareMeter: 680,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "malek",
    alt: "Mr",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 1901,
    bedroomNumber: 6,
    bathroomNumber: 0,
    monthDay: "Month",
    squareMeter: 478,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "omar",
    alt: "Dr",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 1309,
    bedroomNumber: 8,
    bathroomNumber: 4,
    monthDay: "Month",
    squareMeter: 232,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "osama",
    alt: "Mrs",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 6160,
    bedroomNumber: 8,
    bathroomNumber: 8,
    monthDay: "Month",
    squareMeter: 74,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
  {
    name: "tala",
    alt: "Rev",
    typeProperty: "Camp",
    propertyCondition: "For rent",
    price: 9212,
    bedroomNumber: 3,
    bathroomNumber: 7,
    monthDay: "Week",
    squareMeter: 213,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "anas",
    alt: "Honorable",
    typeProperty: "Land",
    propertyCondition: "For sale",
    price: 5122,
    bedroomNumber: 6,
    bathroomNumber: 0,
    monthDay: "Year",
    squareMeter: 48,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "ahmed",
    alt: "Rev",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 6442,
    bedroomNumber: 3,
    bathroomNumber: 1,
    monthDay: "Month",
    squareMeter: 753,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "tala",
    alt: "Rev",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 1903,
    bedroomNumber: 6,
    bathroomNumber: 7,
    monthDay: "Month",
    squareMeter: 284,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "malek",
    alt: "Ms",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 8637,
    bedroomNumber: 10,
    bathroomNumber: 3,
    monthDay: "Month",
    squareMeter: 742,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "osama",
    alt: "Honorable",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 110,
    bedroomNumber: 7,
    bathroomNumber: 0,
    monthDay: "Day",
    squareMeter: 873,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "omar",
    alt: "Dr",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 6915,
    bedroomNumber: 2,
    bathroomNumber: 3,
    monthDay: "Month",
    squareMeter: 445,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "hamza",
    alt: "Dr",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 1011,
    bedroomNumber: 10,
    bathroomNumber: 3,
    monthDay: "Day",
    squareMeter: 251,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "ahmed",
    alt: "Honorable",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 5365,
    bedroomNumber: 9,
    bathroomNumber: 7,
    monthDay: "Week",
    squareMeter: 734,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
  {
    name: "malek",
    alt: "Rev",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 7243,
    bedroomNumber: 5,
    bathroomNumber: 8,
    monthDay: "Month",
    squareMeter: 199,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "osama",
    alt: "Honorable",
    typeProperty: "Land",
    propertyCondition: "For sale",
    price: 9727,
    bedroomNumber: 1,
    bathroomNumber: 8,
    monthDay: "Day",
    squareMeter: 705,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "anas",
    alt: "Rev",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 2671,
    bedroomNumber: 4,
    bathroomNumber: 8,
    monthDay: "Year",
    squareMeter: 170,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "ahmed",
    alt: "Dr",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 9656,
    bedroomNumber: 0,
    bathroomNumber: 3,
    monthDay: "Day",
    squareMeter: 729,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "anas",
    alt: "Mr",
    typeProperty: "Chalet",
    propertyCondition: "For rent",
    price: 2905,
    bedroomNumber: 5,
    bathroomNumber: 5,
    monthDay: "Year",
    squareMeter: 750,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "osama",
    alt: "Rev",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 6168,
    bedroomNumber: 7,
    bathroomNumber: 0,
    monthDay: "Month",
    squareMeter: 310,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "omar",
    alt: "Dr",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 1386,
    bedroomNumber: 0,
    bathroomNumber: 6,
    monthDay: "Day",
    squareMeter: 829,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "hamza",
    alt: "Dr",
    typeProperty: "Chalet",
    propertyCondition: "For rent",
    price: 4994,
    bedroomNumber: 4,
    bathroomNumber: 5,
    monthDay: "Day",
    squareMeter: 15,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
  {
    name: "hamza",
    alt: "Mrs",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 1803,
    bedroomNumber: 3,
    bathroomNumber: 6,
    monthDay: "Week",
    squareMeter: 117,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "tala",
    alt: "Honorable",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 3465,
    bedroomNumber: 9,
    bathroomNumber: 8,
    monthDay: "Day",
    squareMeter: 331,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "anas",
    alt: "Honorable",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 2576,
    bedroomNumber: 6,
    bathroomNumber: 10,
    monthDay: "Day",
    squareMeter: 46,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "malek",
    alt: "Rev",
    typeProperty: "Chalet",
    propertyCondition: "For rent",
    price: 329,
    bedroomNumber: 8,
    bathroomNumber: 10,
    monthDay: "Year",
    squareMeter: 980,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "tala",
    alt: "Ms",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 8795,
    bedroomNumber: 4,
    bathroomNumber: 10,
    monthDay: "Month",
    squareMeter: 560,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "anas",
    alt: "Honorable",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 6290,
    bedroomNumber: 9,
    bathroomNumber: 4,
    monthDay: "Week",
    squareMeter: 43,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
  {
    name: "omar",
    alt: "Mr",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 4729,
    bedroomNumber: 0,
    bathroomNumber: 5,
    monthDay: "Year",
    squareMeter: 961,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "hamza",
    alt: "Mr",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 2258,
    bedroomNumber: 3,
    bathroomNumber: 3,
    monthDay: "Week",
    squareMeter: 843,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "malek",
    alt: "Honorable",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 481,
    bedroomNumber: 4,
    bathroomNumber: 6,
    monthDay: "Day",
    squareMeter: 741,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "osama",
    alt: "Ms",
    typeProperty: "Apartment",
    propertyCondition: "For sale",
    price: 4284,
    bedroomNumber: 0,
    bathroomNumber: 9,
    monthDay: "Year",
    squareMeter: 83,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "malek",
    alt: "Dr",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 167,
    bedroomNumber: 4,
    bathroomNumber: 0,
    monthDay: "Week",
    squareMeter: 571,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
  {
    name: "osama",
    alt: "Mrs",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 3816,
    bedroomNumber: 6,
    bathroomNumber: 9,
    monthDay: "Month",
    squareMeter: 189,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "omar",
    alt: "Honorable",
    typeProperty: "Chalet",
    propertyCondition: "For rent",
    price: 2707,
    bedroomNumber: 10,
    bathroomNumber: 10,
    monthDay: "Month",
    squareMeter: 46,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
  {
    name: "ahmed",
    alt: "Mrs",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 4052,
    bedroomNumber: 6,
    bathroomNumber: 10,
    monthDay: "Month",
    squareMeter: 572,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "anas",
    alt: "Mr",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 4375,
    bedroomNumber: 1,
    bathroomNumber: 1,
    monthDay: "Year",
    squareMeter: 618,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "osama",
    alt: "Ms",
    typeProperty: "Camp",
    propertyCondition: "For rent",
    price: 364,
    bedroomNumber: 4,
    bathroomNumber: 3,
    monthDay: "Day",
    squareMeter: 247,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "osama",
    alt: "Honorable",
    typeProperty: "Camp",
    propertyCondition: "For rent",
    price: 6213,
    bedroomNumber: 2,
    bathroomNumber: 7,
    monthDay: "Year",
    squareMeter: 307,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "malek",
    alt: "Dr",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 539,
    bedroomNumber: 4,
    bathroomNumber: 4,
    monthDay: "Year",
    squareMeter: 733,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "malek",
    alt: "Mrs",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 3143,
    bedroomNumber: 4,
    bathroomNumber: 7,
    monthDay: "Year",
    squareMeter: 461,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "omar",
    alt: "Honorable",
    typeProperty: "Chalet",
    propertyCondition: "For rent",
    price: 4634,
    bedroomNumber: 6,
    bathroomNumber: 8,
    monthDay: "Day",
    squareMeter: 166,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "ahmed",
    alt: "Honorable",
    typeProperty: "Apartment",
    propertyCondition: "For rent",
    price: 6928,
    bedroomNumber: 10,
    bathroomNumber: 7,
    monthDay: "Year",
    squareMeter: 679,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "osama",
    alt: "Ms",
    typeProperty: "Farm",
    propertyCondition: "For rent",
    price: 5780,
    bedroomNumber: 0,
    bathroomNumber: 9,
    monthDay: "Day",
    squareMeter: 80,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "osama",
    alt: "Mrs",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 6783,
    bedroomNumber: 10,
    bathroomNumber: 10,
    monthDay: "Day",
    squareMeter: 221,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "ahmed",
    alt: "Mr",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 9500,
    bedroomNumber: 1,
    bathroomNumber: 6,
    monthDay: "Day",
    squareMeter: 599,
    pets: "yes",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "tala",
    alt: "Honorable",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 4483,
    bedroomNumber: 5,
    bathroomNumber: 4,
    monthDay: "Week",
    squareMeter: 100,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
    ],
  },
  {
    name: "tala",
    alt: "Mr",
    typeProperty: "Land",
    propertyCondition: "For sale",
    price: 3272,
    bedroomNumber: 2,
    bathroomNumber: 8,
    monthDay: "Year",
    squareMeter: 24,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "omar",
    alt: "Rev",
    typeProperty: "Land",
    propertyCondition: "For rent",
    price: 6339,
    bedroomNumber: 3,
    bathroomNumber: 9,
    monthDay: "Year",
    squareMeter: 967,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "anas",
    alt: "Mr",
    typeProperty: "Land",
    propertyCondition: "For sale",
    price: 1171,
    bedroomNumber: 5,
    bathroomNumber: 1,
    monthDay: "Year",
    squareMeter: 115,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "tala",
    alt: "Ms",
    typeProperty: "Camp",
    propertyCondition: "For sale",
    price: 1839,
    bedroomNumber: 6,
    bathroomNumber: 8,
    monthDay: "Year",
    squareMeter: 555,
    pets: "no",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "ahmed",
    alt: "Rev",
    typeProperty: "Land",
    propertyCondition: "For sale",
    price: 9476,
    bedroomNumber: 10,
    bathroomNumber: 6,
    monthDay: "Day",
    squareMeter: 335,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "malek",
    alt: "Ms",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 9706,
    bedroomNumber: 6,
    bathroomNumber: 2,
    monthDay: "Day",
    squareMeter: 365,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Amman",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
    ],
  },
  {
    name: "hamza",
    alt: "Honorable",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 2059,
    bedroomNumber: 1,
    bathroomNumber: 7,
    monthDay: "Week",
    squareMeter: 926,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Amman",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://media.designcafe.com/wp-content/uploads/2023/07/05141750/aesthetic-room-decor.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
    ],
  },
  {
    name: "tala",
    alt: "Dr",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 5006,
    bedroomNumber: 7,
    bathroomNumber: 1,
    monthDay: "Month",
    squareMeter: 801,
    pets: "yes",
    locationPlace: "Tla Al-Ali",
    locationCity: "Irbid",
    src: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3EVqiavem_SlnU6J24GyFBgVOXfRBl4Y7MQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
    ],
  },
  {
    name: "omar",
    alt: "Mrs",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 3446,
    bedroomNumber: 10,
    bathroomNumber: 1,
    monthDay: "Year",
    squareMeter: 517,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV-9i7RqHHw9w3ck_r2JMoKeB8m-R8Aa8hJA&s",
    ],
  },
  {
    name: "anas",
    alt: "Honorable",
    typeProperty: "Farm",
    propertyCondition: "For sale",
    price: 1822,
    bedroomNumber: 2,
    bathroomNumber: 9,
    monthDay: "Month",
    squareMeter: 409,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://img.gathern.co/fit-in/1400x0/1/O14QoBZJfOESVwCvCLrB4cx7fwpj3wyi.jpg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
    ],
  },
  {
    name: "ahmed",
    alt: "Rev",
    typeProperty: "Chalet",
    propertyCondition: "For sale",
    price: 4737,
    bedroomNumber: 1,
    bathroomNumber: 7,
    monthDay: "Week",
    squareMeter: 740,
    pets: "no",
    locationPlace: "Bassman",
    locationCity: "Irbid",
    src: [
      "https://img.gathern.co/1/hamgmhQ6IDlleoYXmFFm9XLvdFazunih.jpeg",
      "https://lp-cms-production.imgix.net/2021-01/GettyRF_450207051.jpg?auto=format&w=1440&h=810&fit=crop&q=75",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT1vnEZlC__BdhCIzBrOYFYJ4pbuDNa0IS9w&s",
    ],
  },
];
